### ISSUE TITLE
Error popup

### ISSUE THREAD

**Issue by liujvnes** [DimaChaichan/LAizypainter#2]
I just installed the plug-in, but I still get an error when I don’t know how to use it.Please help.
![屏幕截图 2024-04-13 000035](https://github.com/DimaChaichan/LAizypainter/assets/25132014/4402cc91-37cc-4200-9ecf-964599859811)

**Comment by DimaChaichan** [comment]
Hello liujvnes, 
this message is from ComfyUI. Looks like the node "Foooocus" has a problem.
The task has probably not been created correctly. Can you send it to me? 

Currently the task creation is a bit difficult, I will adjust this sometime. 
Otherwise you can activate the debug mode and see what the request looks like that LaizyPainter sends to ComfyUI.
https://github.com/DimaChaichan/LAizypainter?tab=readme-ov-file#debug-mode

Best regards

**Comment by liujvnes** [comment]
> Hello liujvnes, this message is from ComfyUI. Looks like the node "Foooocus" has a problem. The task has probably not been created correctly. Can you send it to me?
> 
> Currently the task creation is a bit difficult, I will adjust this sometime. Otherwise you can activate the debug mode and see what the request looks like that LaizyPainter sends to ComfyUI. https://github.com/DimaChaichan/LAizypainter?tab=readme-ov-file#debug-mode
> 
> Best regards
[fooocus_api.json](https://github.com/DimaChaichan/LAizypainter/files/14980785/fooocus_api.json)

**Comment by DimaChaichan** [comment]
Hello liujvnes,

the json file looks correct at first glance. As I don't have your setup I can't test it. Try to make an API Comfy call : https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py 

It may be that the Fooocus_node has problems with the API call. Then you have to contact the developer of the Fooocus_node.

Best regards
